// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: drone.proto
// Protobuf C++ Version: 5.29.5

#ifndef drone_2eproto_2epb_2eh
#define drone_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_drone_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_drone_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_drone_2eproto;
class DroneTelemetry;
struct DroneTelemetryDefaultTypeInternal;
extern DroneTelemetryDefaultTypeInternal _DroneTelemetry_default_instance_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class DroneTelemetry final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:DroneTelemetry) */ {
 public:
  inline DroneTelemetry() : DroneTelemetry(nullptr) {}
  ~DroneTelemetry() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(DroneTelemetry* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(DroneTelemetry));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR DroneTelemetry(
      ::google::protobuf::internal::ConstantInitialized);

  inline DroneTelemetry(const DroneTelemetry& from) : DroneTelemetry(nullptr, from) {}
  inline DroneTelemetry(DroneTelemetry&& from) noexcept
      : DroneTelemetry(nullptr, std::move(from)) {}
  inline DroneTelemetry& operator=(const DroneTelemetry& from) {
    CopyFrom(from);
    return *this;
  }
  inline DroneTelemetry& operator=(DroneTelemetry&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DroneTelemetry& default_instance() {
    return *internal_default_instance();
  }
  static inline const DroneTelemetry* internal_default_instance() {
    return reinterpret_cast<const DroneTelemetry*>(
        &_DroneTelemetry_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(DroneTelemetry& a, DroneTelemetry& b) { a.Swap(&b); }
  inline void Swap(DroneTelemetry* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DroneTelemetry* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DroneTelemetry* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<DroneTelemetry>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const DroneTelemetry& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const DroneTelemetry& from) { DroneTelemetry::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(DroneTelemetry* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "DroneTelemetry"; }

 protected:
  explicit DroneTelemetry(::google::protobuf::Arena* arena);
  DroneTelemetry(::google::protobuf::Arena* arena, const DroneTelemetry& from);
  DroneTelemetry(::google::protobuf::Arena* arena, DroneTelemetry&& from) noexcept
      : DroneTelemetry(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kLatFieldNumber = 2,
    kLonFieldNumber = 3,
    kDroneIdFieldNumber = 1,
    kVxFieldNumber = 5,
    kAltFieldNumber = 4,
    kVyFieldNumber = 6,
    kVzFieldNumber = 7,
  };
  // double lat = 2;
  void clear_lat() ;
  double lat() const;
  void set_lat(double value);

  private:
  double _internal_lat() const;
  void _internal_set_lat(double value);

  public:
  // double lon = 3;
  void clear_lon() ;
  double lon() const;
  void set_lon(double value);

  private:
  double _internal_lon() const;
  void _internal_set_lon(double value);

  public:
  // uint32 drone_id = 1;
  void clear_drone_id() ;
  ::uint32_t drone_id() const;
  void set_drone_id(::uint32_t value);

  private:
  ::uint32_t _internal_drone_id() const;
  void _internal_set_drone_id(::uint32_t value);

  public:
  // float vx = 5;
  void clear_vx() ;
  float vx() const;
  void set_vx(float value);

  private:
  float _internal_vx() const;
  void _internal_set_vx(float value);

  public:
  // double alt = 4;
  void clear_alt() ;
  double alt() const;
  void set_alt(double value);

  private:
  double _internal_alt() const;
  void _internal_set_alt(double value);

  public:
  // float vy = 6;
  void clear_vy() ;
  float vy() const;
  void set_vy(float value);

  private:
  float _internal_vy() const;
  void _internal_set_vy(float value);

  public:
  // float vz = 7;
  void clear_vz() ;
  float vz() const;
  void set_vz(float value);

  private:
  float _internal_vz() const;
  void _internal_set_vz(float value);

  public:
  // @@protoc_insertion_point(class_scope:DroneTelemetry)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 7, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const DroneTelemetry& from_msg);
    double lat_;
    double lon_;
    ::uint32_t drone_id_;
    float vx_;
    double alt_;
    float vy_;
    float vz_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_drone_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// DroneTelemetry

// uint32 drone_id = 1;
inline void DroneTelemetry::clear_drone_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.drone_id_ = 0u;
}
inline ::uint32_t DroneTelemetry::drone_id() const {
  // @@protoc_insertion_point(field_get:DroneTelemetry.drone_id)
  return _internal_drone_id();
}
inline void DroneTelemetry::set_drone_id(::uint32_t value) {
  _internal_set_drone_id(value);
  // @@protoc_insertion_point(field_set:DroneTelemetry.drone_id)
}
inline ::uint32_t DroneTelemetry::_internal_drone_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.drone_id_;
}
inline void DroneTelemetry::_internal_set_drone_id(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.drone_id_ = value;
}

// double lat = 2;
inline void DroneTelemetry::clear_lat() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.lat_ = 0;
}
inline double DroneTelemetry::lat() const {
  // @@protoc_insertion_point(field_get:DroneTelemetry.lat)
  return _internal_lat();
}
inline void DroneTelemetry::set_lat(double value) {
  _internal_set_lat(value);
  // @@protoc_insertion_point(field_set:DroneTelemetry.lat)
}
inline double DroneTelemetry::_internal_lat() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.lat_;
}
inline void DroneTelemetry::_internal_set_lat(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.lat_ = value;
}

// double lon = 3;
inline void DroneTelemetry::clear_lon() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.lon_ = 0;
}
inline double DroneTelemetry::lon() const {
  // @@protoc_insertion_point(field_get:DroneTelemetry.lon)
  return _internal_lon();
}
inline void DroneTelemetry::set_lon(double value) {
  _internal_set_lon(value);
  // @@protoc_insertion_point(field_set:DroneTelemetry.lon)
}
inline double DroneTelemetry::_internal_lon() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.lon_;
}
inline void DroneTelemetry::_internal_set_lon(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.lon_ = value;
}

// double alt = 4;
inline void DroneTelemetry::clear_alt() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.alt_ = 0;
}
inline double DroneTelemetry::alt() const {
  // @@protoc_insertion_point(field_get:DroneTelemetry.alt)
  return _internal_alt();
}
inline void DroneTelemetry::set_alt(double value) {
  _internal_set_alt(value);
  // @@protoc_insertion_point(field_set:DroneTelemetry.alt)
}
inline double DroneTelemetry::_internal_alt() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.alt_;
}
inline void DroneTelemetry::_internal_set_alt(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.alt_ = value;
}

// float vx = 5;
inline void DroneTelemetry::clear_vx() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.vx_ = 0;
}
inline float DroneTelemetry::vx() const {
  // @@protoc_insertion_point(field_get:DroneTelemetry.vx)
  return _internal_vx();
}
inline void DroneTelemetry::set_vx(float value) {
  _internal_set_vx(value);
  // @@protoc_insertion_point(field_set:DroneTelemetry.vx)
}
inline float DroneTelemetry::_internal_vx() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.vx_;
}
inline void DroneTelemetry::_internal_set_vx(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.vx_ = value;
}

// float vy = 6;
inline void DroneTelemetry::clear_vy() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.vy_ = 0;
}
inline float DroneTelemetry::vy() const {
  // @@protoc_insertion_point(field_get:DroneTelemetry.vy)
  return _internal_vy();
}
inline void DroneTelemetry::set_vy(float value) {
  _internal_set_vy(value);
  // @@protoc_insertion_point(field_set:DroneTelemetry.vy)
}
inline float DroneTelemetry::_internal_vy() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.vy_;
}
inline void DroneTelemetry::_internal_set_vy(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.vy_ = value;
}

// float vz = 7;
inline void DroneTelemetry::clear_vz() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.vz_ = 0;
}
inline float DroneTelemetry::vz() const {
  // @@protoc_insertion_point(field_get:DroneTelemetry.vz)
  return _internal_vz();
}
inline void DroneTelemetry::set_vz(float value) {
  _internal_set_vz(value);
  // @@protoc_insertion_point(field_set:DroneTelemetry.vz)
}
inline float DroneTelemetry::_internal_vz() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.vz_;
}
inline void DroneTelemetry::_internal_set_vz(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.vz_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // drone_2eproto_2epb_2eh
